# Generated by Django 5.2.4 on 2025-08-01 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watched',
            name='movie',
        ),
        migrations.AddField(
            model_name='watched',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='watched',
            name='title',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
